# Generated by Django 4.2.3 on 2023-08-17 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('DEPTNO', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('DNAME', models.CharField(max_length=50, unique=True)),
                ('LOCATION', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('EMPNO', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('ENAME', models.CharField(max_length=50)),
                ('JOB', models.CharField(max_length=25)),
                ('HIREDATE', models.DateField()),
                ('SALARY', models.IntegerField()),
                ('COMM', models.IntegerField(null=True)),
                ('DEPTNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
